import React, { useState, useEffect } from 'react';
import { DollarSign, Plus, Clock, CheckCircle, X } from 'lucide-react';
import { auth } from '../../../firebaseConfig';
import styles from './AddFund.module.css'; // ✅ Module CSS import

const AddFund = ({ 
  currentBalance, 
  pendingBalance, 
  userBkashNumber, 
  onAddPendingBalance,
  onBalanceUpdate
}) => {
  const [addAmount, setAddAmount] = useState('');
  const [senderNumber, setSenderNumber] = useState('');
  const [paymentLoading, setPaymentLoading] = useState(false);
  const [paymentError, setPaymentError] = useState('');
  const [successMessage, setSuccessMessage] = useState('');
  const [user, setUser] = useState(null);

  // Math challenge state
  const [showMathChallenge, setShowMathChallenge] = useState(false);
  const [mathQuestion, setMathQuestion] = useState('');
  const [mathAnswer, setMathAnswer] = useState('');
  const [userMathAnswer, setUserMathAnswer] = useState('');

  // Quick amount buttons
  const quickAmounts = [1000, 2000, 3000, 5000, 10000];

  // Get current user from Firebase
  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((currentUser) => {
      if (currentUser) {
        setUser(currentUser);
        console.log('🔥 Firebase User in AddFund:', currentUser.email);
      } else {
        setUser(null);
      }
    });

    return () => unsubscribe();
  }, []);

  // Generate random math question
  const generateMathQuestion = () => {
    const num1 = Math.floor(Math.random() * 10) + 1;
    const num2 = Math.floor(Math.random() * 10) + 1;
    const question = `${num1} + ${num2} = ?`;
    const answer = (num1 + num2).toString();
    
    setMathQuestion(question);
    setMathAnswer(answer);
    setUserMathAnswer('');
    return { question, answer };
  };

  // Validate phone number
  const validatePhoneNumber = (phone) => {
    if (!phone.trim()) return false;
    const phoneRegex = /^(?:\+88|01)?(?:\d{11}|\d{13})$/;
    return phoneRegex.test(phone.replace(/\s+/g, ''));
  };

  // Get API base URL
  const getApiBaseUrl = () => {
    return '/api';
  };

  // ✅ Generate unique transaction ID based on timestamp + random
  const generateTransactionId = () => {
    const timestamp = Date.now().toString(36).toUpperCase();
    const random = Math.random().toString(36).substring(2, 6).toUpperCase();
    return `C${timestamp}${random}`;
  };

  // Handle balance add request
  const handleAddBalance = async (e) => {
    e.preventDefault();
    
    if (!user) {
      setPaymentError('দয়া করে প্রথমে লগইন করুন!');
      return;
    }

    const amount = parseFloat(addAmount);
    
    if (isNaN(amount) || amount <= 0) {
      setPaymentError('দয়া করে সঠিক অ্যামাউন্ট লিখুন!');
      return;
    }

    if (amount < 10) {
      setPaymentError('ন্যূনতম ১০ টাকা যোগ করতে হবে!');
      return;
    }

    if (!senderNumber.trim()) {
      setPaymentError('দয়া করে আপনার bKash নম্বর দিন!');
      return;
    }

    if (!validatePhoneNumber(senderNumber)) {
      setPaymentError('bKash নম্বর সঠিক নয়! 11 ডিজিটের নম্বর দিন (যেমন: 01712345678)');
      return;
    }

    generateMathQuestion();
    setShowMathChallenge(true);
  };

  // Handle math challenge submission
  const handleMathChallengeSubmit = async () => {
    if (!userMathAnswer.trim()) {
      setPaymentError('দয়া করে গাণিতিক প্রশ্নের উত্তর দিন!');
      return;
    }

    if (userMathAnswer !== mathAnswer) {
      setPaymentError(`গাণিতিক প্রশ্নের উত্তর ভুল হয়েছে! সঠিক উত্তর: ${mathAnswer}`);
      setUserMathAnswer('');
      return;
    }

    setPaymentLoading(true);
    setPaymentError('');
    setSuccessMessage('');

    try {
      const amount = parseFloat(addAmount);
      const API_BASE_URL = getApiBaseUrl();
      
      // ✅ Auto-generate transaction ID
      const autoGeneratedTrxId = generateTransactionId();
      
      const paymentData = {
        amount: amount,
        transactionId: autoGeneratedTrxId, // ✅ Auto-generated
        senderNumber: senderNumber.trim(),
        userBkashNumber: userBkashNumber || '01766325020',
        user: {
          uid: user.uid,
          email: user.email,
          displayName: user.displayName,
          phoneNumber: user.phoneNumber
        },
        mathQuestion: mathQuestion,
        mathAnswer: mathAnswer,
        userMathAnswer: userMathAnswer,
        status: 'pending',
        timestamp: new Date().toISOString()
      };

      console.log('💰 Payment Request Details:', paymentData);
      console.log('🌐 API URL:', `${API_BASE_URL}/payments/create`);

      const response = await fetch(`${API_BASE_URL}/payments/create`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(paymentData)
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('❌ Server error response:', errorText);
        throw new Error(`Server error: ${response.status} ${response.statusText}`);
      }

      const result = await response.json();
      console.log('✅ Backend Response:', result);

      if (!result.success) {
        throw new Error(result.message || 'পেমেন্ট সাবমিট করতে সমস্যা হয়েছে');
      }

      if (onAddPendingBalance) {
        onAddPendingBalance(paymentData);
      }

      if (onBalanceUpdate) {
        onBalanceUpdate({
          pendingBalance: (pendingBalance || 0) + amount
        });
      }

      setSuccessMessage(`৳ ${amount.toLocaleString()} পেন্ডিং ব্যালেন্সে যোগ হয়েছে! রেফারেন্স নম্বর: ${autoGeneratedTrxId}. অ্যাডমিন ভেরিফাই করার পর এভেইলেবল হবে।`);
      
      setAddAmount('');
      setSenderNumber('');
      setUserMathAnswer('');
      setShowMathChallenge(false);
      
    } catch (error) {
      console.error('❌ Payment error:', error);
      
      if (error.message.includes('Failed to fetch')) {
        setPaymentError('বেকেন্ড সার্ভারে কানেক্ট হতে পারছি না। দয়া করে আবার চেষ্টা করুন।');
      } else if (error.message.includes('Server error')) {
        setPaymentError('সার্ভারে সমস্যা হচ্ছে। দয়া করে কিছুক্ষণ পর আবার চেষ্টা করুন।');
      } else {
        setPaymentError(error.message || 'পেমেন্ট সাবমিট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।');
      }
    } finally {
      setPaymentLoading(false);
    }
  };

  // Handle quick amount selection
  const handleQuickAmount = (amount) => {
    setAddAmount(amount.toString());
    setPaymentError('');
    setSuccessMessage('');
  };

  if (!user) {
    return (
      <div className={styles.addFundContainer}>
        <div className={styles.loadingSpinner}>
          <div className={styles.spinner}></div>
          <p>লোড হচ্ছে...</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.addFundContainer}>
      {/* User Info Display */}
      {user && (
        <div className={styles.userInfoCard}>
          <div className={styles.userInfo}>
            <strong>ইউজার:</strong> {user.email}
            {user.displayName && <span> | {user.displayName}</span>}
          </div>
        </div>
      )}

      {/* Balance Cards */}
      <div className={styles.balanceCards}>
        {/* Available Balance Card */}
        <div className={`${styles.balanceCard} ${styles.available}`}>
          <div className={styles.balanceHeader}>
            <DollarSign size={24} className={styles.balanceIcon} />
            <div className={styles.balanceInfo}>
              <h4>এভেইলেবল ব্যালেন্স</h4>
              <div className={styles.balanceAmount}>৳ {currentBalance?.toFixed(2) || '0.00'}</div>
            </div>
          </div>
          <p className={styles.balanceNote}>
            এই ব্যালেন্স দিয়ে এখনই অর্ডার করতে পারবেন
          </p>
        </div>

        {/* Pending Balance Card */}
        <div className={`${styles.balanceCard} ${styles.pending}`}>
          <div className={styles.balanceHeader}>
            <Clock size={24} className={styles.balanceIcon} />
            <div className={styles.balanceInfo}>
              <h4>পেন্ডিং ব্যালেন্স</h4>
              <div className={styles.balanceAmount}>৳ {pendingBalance?.toFixed(2) || '0.00'}</div>
            </div>
          </div>
          <p className={styles.balanceNote}>
            অ্যাডমিন ভেরিফাই করার পর এভেইলেবল হবে
          </p>
        </div>
      </div>

      {/* Math Challenge Modal */}
      {showMathChallenge && (
        <div className={styles.mathChallengeModal}>
          <div className={styles.mathChallengeContent}>
            <h3>সিকিউরিটি ভেরিফিকেশন</h3>
            <p>নিচের গাণিতিক প্রশ্নের উত্তর দিন:</p>
            
            <div className={styles.mathQuestion}>
              <strong>{mathQuestion}</strong>
            </div>
            
            <div className={styles.formGroup}>
              <input
                type="text"
                placeholder="উত্তর লিখুন (সংখ্যা)"
                value={userMathAnswer}
                onChange={(e) => setUserMathAnswer(e.target.value.replace(/[^0-9]/g, ''))}
                disabled={paymentLoading}
                className={styles.mathInput}
              />
            </div>

            <div className={styles.mathChallengeButtons}>
              <button
                onClick={handleMathChallengeSubmit}
                disabled={paymentLoading || !userMathAnswer}
                className={styles.submitChallengeBtn}
              >
                {paymentLoading ? (
                  <>
                    <div className={styles.spinner}></div>
                    প্রসেসিং...
                  </>
                ) : (
                  'ভেরিফাই করুন'
                )}
              </button>
              
              <button
                onClick={() => {
                  setShowMathChallenge(false);
                  setUserMathAnswer('');
                }}
                className={styles.cancelChallengeBtn}
                disabled={paymentLoading}
              >
                বাতিল
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Add Balance Section */}
      <div className={styles.addBalanceSection}>
        <h4>bKash এর মাধ্যমে ব্যালেন্স যোগ করুন</h4>
        
        {paymentError && (
          <div className={styles.paymentError}>
            <X size={18} />
            {paymentError}
          </div>
        )}

        {successMessage && (
          <div className={styles.successMessage}>
            <CheckCircle size={18} />
            {successMessage}
          </div>
        )}

        {/* Quick Amount Buttons */}
        <div className={styles.quickAmountSection}>
          <h5>দ্রুত নির্বাচন করুন:</h5>
          <div className={styles.quickAmountButtons}>
            {quickAmounts.map(amount => (
              <button
                key={amount}
                type="button"
                className={`${styles.quickAmountBtn} ${addAmount === amount.toString() ? styles.selected : ''}`}
                onClick={() => handleQuickAmount(amount)}
                disabled={paymentLoading}
              >
                ৳ {amount.toLocaleString()}
              </button>
            ))}
          </div>
        </div>

        {/* Custom Amount Form */}
        <form onSubmit={handleAddBalance} className={styles.addBalanceForm}>
          <div className={styles.formGroup}>
            <label>কাস্টম অ্যামাউন্ট</label>
            <input 
              type="number" 
              placeholder="কত টাকা যোগ করতে চান?"
              value={addAmount}
              onChange={(e) => {
                setAddAmount(e.target.value);
                setPaymentError('');
                setSuccessMessage('');
              }}
              min="10"
              step="1"
              required
              disabled={paymentLoading}
              className={styles.amountInput}
            />
            <small>ন্যূনতম ১০ টাকা যোগ করতে হবে</small>
          </div>

          <div className={styles.formGroup}>
            <label>আপনার bKash নম্বর</label>
            <input 
              type="tel" 
              placeholder="আপনার bKash নম্বর (যেমন: 017xxxxxxxx)"
              value={senderNumber}
              onChange={(e) => {
                setSenderNumber(e.target.value);
                setPaymentError('');
                setSuccessMessage('');
              }}
              required
              disabled={paymentLoading}
              className={styles.phoneInput}
              style={{
                borderColor: senderNumber && !validatePhoneNumber(senderNumber) ? '#dc3545' : '#d1d5db',
                color: senderNumber && !validatePhoneNumber(senderNumber) ? '#dc3545' : '#1a1a1a'
              }}
            />
            <small>
              {senderNumber && !validatePhoneNumber(senderNumber) 
                ? '⚠️ bKash নম্বর সঠিক নয় (11 ডিজিটের নম্বর দিন)' 
                : 'যে bKash নম্বর থেকে টাকা পাঠাবেন সেই নম্বর দিন'}
            </small>
          </div>
          
          <button 
            type="submit" 
            className={styles.addBalanceBtn}
            disabled={paymentLoading || !addAmount || !senderNumber || parseFloat(addAmount) < 10 || !validatePhoneNumber(senderNumber)}
          >
            {paymentLoading ? (
              <>
                <div className={styles.spinner}></div>
                প্রসেসিং...
              </>
            ) : (
              <>
                <Plus size={18} />
                ৳ {addAmount || '0'} যোগ করুন
              </>
            )}
          </button>
        </form>

        {/* Payment Instructions */}
        <div className={styles.paymentInstructions}>
          <h5>পেমেন্ট নির্দেশনা:</h5>
          <ol>
            <li>উপরে অ্যামাউন্ট সিলেক্ট করুন (ন্যূনতম ১০ টাকা)</li>
            <li><strong>bKash App এ গিয়ে 01766325020 নম্বরে Send Money করুন</strong></li>
            <li>যে bKash নম্বর থেকে টাকা পাঠিয়েছেন সেই নম্বর দিন</li>
            <li>গাণিতিক প্রশ্নের উত্তর দিন (সিকিউরিটি যাচাই)</li>
            <li>ভেরিফাই করুন - অ্যামাউন্ট পেন্ডিং ব্যালেন্সে যোগ হবে</li>
            <li>অ্যাডমিন আপনার bKash নম্বর চেক করে ভেরিফাই করবে</li>
            <li>ভেরিফাই হলে ব্যালেন্স এভেইলেবল হয়ে যাবে</li>
          </ol>
          
          <div className={styles.importantNote}>
            <strong>⚠️ গুরুত্বপূর্ণ:</strong> অবশ্যই আপনার নিজের bKash নম্বর থেকে Send Money করবেন। অ্যাডমিন সেই নম্বর দিয়েই ভেরিফাই করবে।
          </div>
        </div>
      </div>
    </div>
  );
};

export default AddFund;